### ISSUE TITLE
how do you stop the Pulsar? and 1 pulsar per?

### ISSUE THREAD

**Issue by eliteproxy7** [regexident/Pulsar#1]
if I initiate it how can I stop it?

also, when I call view.addPulsar is there a way if limit it to 1 addPulsar? when I run addPulsar multiple times on a view it adds multiple pulsars

**Comment by regexident** [comment]
> if I initiate it how can I stop it?

I just added a function (to v1.1.0)

``` swift
public func removePulse(pulse: CAShapeLayer)
```

which allows the removal of pulses returned from calls to

``` swift
public func addPulse(closure: PulsarClosure? = nil) -> CAShapeLayer?
```

> also, when I call view.addPulsar is there a way if limit it to 1 addPulsar?

Yes there is. Just don't call it twice. 😉 

> when I run addPulsar multiple times on a view it adds multiple pulsars

That's expected behavior. Otherwise the function would be called `setPulse(…)`.

Given your confusion I reckon you might be looking for [repeated pulses](https://github.com/regexident/Pulsar/blob/master/PulsarDemo/ViewController.swift#L44-L45) instead?
